#!/bin/bash

# Set the following variables correspondingly to run this script:

################## VICUNA ##################
PROMPT_VERSION=v1

# Prefer the local SelfSynthX checkpoint if available; else fall back to HF.
SELF_SYNTHX_LLAVA="/home/csgrad/mbhosale/phd/MrFair/SelfSynthX/llava-1.5-7b-hf"
if [ -d "$SELF_SYNTHX_LLAVA" ]; then
    model_base="${MODEL_BASE:-$SELF_SYNTHX_LLAVA}"
else
    model_base="${MODEL_BASE:-liuhaotian/llava-v1.5-7b}"
fi

output_dir="${1:-./checkpoints}"

# Must match the projector you pretrained for HAM10000.
# Example:
export PROJECTOR="/home/csgrad/mbhosale/phd/MrFair/LLaVA-Rad/checkpoints/openai/clip-vit-large-patch14-336-ham10000-mmproj-1e-2e-4-20260124234451/mm_projector.bin"
PROJECTOR="${PROJECTOR:-}"
if [ -z "$PROJECTOR" ]; then
    echo "ERROR: PROJECTOR is not set. Export PROJECTOR=/path/to/mm_projector.bin" >&2
    exit 2
fi

# Must match whatever you used during projector pretraining.
vision_tower="${VISION_TOWER:-openai/clip-vit-large-patch14-336}"
################## VICUNA ##################


################## Data ##################
# Generated by: scripts/prepare_ham10000_qa_llava_json.py (write split files)
data_path="${DATA_PATH:-/data_local1/mbhosale/MrFair/HAM10000/HAM10000_round3_qa_llava_train.json}"
loader="${LOADER:-ham10000_train_qa}"

# IMPORTANT:
# The converter stores `image` as a path relative to --image_folder.
# If your JSON has "image": "ISIC2018_Task3_Training_Input/ISIC_....jpg",
# then IMAGE_FOLDER should be the HAM10000 root folder.
image_folder="${IMAGE_FOLDER:-/data_local1/mbhosale/MrFair/HAM10000}"
################## Data ##################

################## Run name ##################
epoch="${2:-3}"
bsz="${3:-6}"
grad_acc="${4:-2}"
lr="${LR:-1e-4}"
schedule="lora-${epoch}e"

# Reproducibility
seed="${SEED:-42}"

# Optional tag to help identify ablation runs
run_tag="${RUN_TAG:-}"
if [ -n "$run_tag" ]; then
    export run_name="${vision_tower}-${schedule}-${lr}-${run_tag}-$(date +%Y%m%d%H%M%S)"
else
    export run_name="${vision_tower}-${schedule}-${lr}-$(date +%Y%m%d%H%M%S)"
fi
echo $run_name > run_name
################## Run name ##################


# Fairness finetune (MI/CLUB debiasing)
FAIRNESS_CONFIG="${FAIRNESS_CONFIG:-/home/csgrad/mbhosale/phd/MrFair/LLaVA-Rad/configs/fairness_finetune_ham10000_mi_stronger.json}"

WANDB_PROJECT="llava" WANDB_RUN_ID="llava-ft-ham10000-$(date +%Y%m%d%H%M%S)" WANDB_RUN_GROUP=fine-tune \
    deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --lora_enable True \
    --lora_alpha 128 \
    --model_name_or_path ${model_base} \
    --version $PROMPT_VERSION \
    --data_path ${data_path} \
    --loader ${loader} \
    --image_folder ${image_folder} \
    --vision_tower ${vision_tower} \
    --pretrain_mm_mlp_adapter ${PROJECTOR} \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ${output_dir}/${run_name} \
    --num_train_epochs ${epoch} \
    --per_device_train_batch_size ${bsz} \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps ${grad_acc} \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 5 \
    --learning_rate ${lr} \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 10 \
    --seed ${seed} \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --dataloader_num_workers 8 \
    --report_to wandb \
    --run_name ${run_name} \
    --output_hidden_states True \
    --fairness_finetune True \
    --fairness_labels True \
    --fairness_config ${FAIRNESS_CONFIG}
