#!/bin/bash

# Script to pretrain the mmmlp adapter (mm_projector) for further finetuning stage.

set -e

# Prefer the local SelfSynthX checkpoint if available; else fall back to HF.
SELF_SYNTHX_LLAVA="/home/csgrad/mbhosale/phd/MrFair/SelfSynthX/llava-1.5-7b-hf"
if [ -d "$SELF_SYNTHX_LLAVA" ]; then
  model_base="${MODEL_BASE:-$SELF_SYNTHX_LLAVA}"
else
  model_base="${MODEL_BASE:-liuhaotian/llava-v1.5-7b}"
fi

output_dir="${1:-./checkpoints}"

# HAM10000 QA dataset converted to LLaVA conversations + demographics
# Generated by: scripts/prepare_ham10000_qa_llava_json.py
DATA_PATH_DEFAULT="/data_local1/mbhosale/MrFair/HAM10000/HAM10000_round3_qa_llava_train.json"
data_path="${DATA_PATH:-$DATA_PATH_DEFAULT}"
loader="${LOADER:-ham10000_train_qa}"
image_folder="${IMAGE_FOLDER:-/data_local1/mbhosale/MrFair/HAM10000/}"

################## Run name ##################
# Vision tower: SelfSynthX uses LLaVA-1.5 HF; default vision tower matches that.
# Override if you want a derm-specific encoder.
vision_tower="${VISION_TOWER:-openai/clip-vit-large-patch14-336}"

epoch="${2:-1}"
bsz="${3:-8}"
grad_acc="${4:-11}"

lr="${LR:-2e-4}"
schedule="ham10000-mmproj-${epoch}e"
run_name="${RUN_NAME:-${vision_tower}-${schedule}-${lr}-$(date +%Y%m%d%H%M%S)}"
echo "$run_name" > run_name
################## Run name ##################

WANDB_RUN_ID="llava-pt-ham10000-$(date +%Y%m%d%H%M%S)" WANDB_PROJECT="llava" WANDB_RUN_GROUP=pre-train \
  deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path "${model_base}" \
    --version plain \
    --data_path "${data_path}" \
    --loader "${loader}" \
    --image_folder "${image_folder}" \
    --vision_tower "${vision_tower}" \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir "${output_dir}/${run_name}" \
    --num_train_epochs "${epoch}" \
    --per_device_train_batch_size "${bsz}" \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps "${grad_acc}" \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_total_limit 2 \
    --learning_rate "${lr}" \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 10 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to wandb \
    --run_name "${run_name}"
